workspace: dspsim.cywrk
projects:
  # USBBootloader: psoc/USBBootloader.cydsn
  USBBridge: psoc/USBBridge.cydsn

build_type: Release
output_files:
  - "*.hex"
  - "*.cyacd"


psoc_creator_location: "C:/Program Files (x86)/Cypress/PSoC Creator"
psoc_creator_version: 4.4

# Options for PSoC5
arch: "CortexM3"
compiler: "ARM_GCC_541"
