[build-system]
requires = [
    "scikit-build-core>=1.0.3",
    "nanobind>=3.0.1",
    "nanobind-backend>=1.0.0",
    "verilator-dspsim>=5.52.0",
    "jinja2>=3.1.6",
]
build-backend = "scikit_build_core.build"

[project]
name = "dspsim"
version = "0.4.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Frank" }
]
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Programming Language :: C++",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
]
requires-python = ">=3.14"
dependencies = [
    "jinja2>=3.1.6",
    "nanobind>=3.0.1",
    "nanobind-backend>=1.0.0",
    "numpy>=2.5.2",
]

[project.optional-dependencies]
verilator = [
    "verilator-dspsim>=5.52.0",
]

[project.scripts]
dspsim = "dspsim:main"

[tool.scikit-build]
minimum-version = "build-system.requires"
build-dir = "build"
wheel.packages = ["src/dspsim"]

[tool.uv]
cache-keys = [
    { file = "pyproject.toml" },
    { file = "src/**/*.{h,c,hpp,cpp,v,sv}" },
    { file = "CMakeLists.txt" },
    {file = "src/CMakeLists.txt"}
]

[dependency-groups]
dev = [
    "nanobind>=3.0.1",
    "nanobind-backend>=1.0.0",
    "pytest>=9.1.1",
    "ruff>=0.16.5",
    "scikit-build-core>=1.0.3",
    "verilator-dspsim>=5.52.0",
]




# Generate binding code for modules.

#---------------------------------------------------------------------------------------------------#
#---------------------------------------------------------------------------------------------------#

# dspsim tool configuration for the library module.
[tool.dspsim]
name = "library"
# Use all sources in the dspsim/hdl directory.
sources = ["src/dspsim/hdl/*.sv", "src/dspsim/hdl/*.v"]
exclude_sources = ["src/dspsim/hdl/HellModel.sv"]
# sources = ["src/dspsim/hdl/SimpleModel.sv"]
include_dirs = []
include_dspsim_library = true
# Can use fst on linux.
trace = "vcd"
# parameters = { DW = 24, CFGAW = 32, CFGDW = 32, COEFW = 18, COEFQ = 16 }

# Global parameters applied to all modules.
[tool.dspsim.parameters]
DW = 24
CFGAW = 32
CFGDW = 32
COEFW = 18
COEFQ = 16

[tool.dspsim.models]
SimpleModel = {source = "SimpleModel.sv", parameters = { DW = 32 } }
SimpleModel16 = {source = "SimpleModel.sv", parameters = { DW = 16 } }

[tool.dspsim.models.SimpleModel8]
source = "SimpleModel.sv"
parameters = { DW = 8 }
trace = "None"

#---------------------------------------------------------------------------------------------------#
#---------------------------------------------------------------------------------------------------#
