[build-system]
requires = [
    "scikit-build-core>=1.0.3",
    "nanobind>=3.0.1",
    "nanobind-backend>=1.0.0",
]
build-backend = "scikit_build_core.build"

[project]
name = "dspsim"
version = "0.5.3"
description = "discrete-event simulation engine for HDL designs."
readme = "README.md"
authors = [
    { name = "Frank Sodari" }
]
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Programming Language :: C++",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
]
requires-python = ">=3.14"
dependencies = [
    "jinja2>=3.1.6",
    "nanobind>=3.0.1",
    "nanobind-backend>=1.0.0",
    "numpy>=2.5.2",
]

[project.optional-dependencies]
verilator = [
    "verilator-dspsim>=5.52.0",
]
# library = ["dspsim-library>="]

[project.scripts]
dspsim = "dspsim.framework.cli:main"

[tool.scikit-build]
minimum-version = "build-system.requires"
wheel.packages = ["src/dspsim"]
build.targets =["_framework"]
cmake.build-type = "Debug"

[tool.uv]
cache-keys = [
    { file = "pyproject.toml" },
    { file = "src/**/*.{h,c,hpp,cpp,v,sv}" },
    { file = "CMakeLists.txt" },
    { file = "src/CMakeLists.txt" }
]

[dependency-groups]
dev = [
    "nanobind>=3.0.1",
    "nanobind-backend>=1.0.0",
    "pytest>=9.1.1",
    "ruff>=0.16.5",
    "scikit-build-core>=1.0.3",
    "verilator-dspsim>=5.52.0",
]

###
### Cibuildwheel config
###
[tool.cibuildwheel]
# 64 bit builds
archs = ["auto64"]
# Python3.12+. Older versions should work?
build = ["cp314-*"]
# Don't build arm. Use only > cp39, no PyPy. Not using musl anywhere so no musl (it works though?)
skip = ["*cp314t*","*-win_arm64", "*musllinux*"]

# Run pytest to ensure that the package was build correctly
test-command = "pytest {project}/tests"
test-requires = "pytest verilator-dspsim"
build-verbosity = 1

###
###
###
