[build-system]
requires = [
    "scikit-build-core>=1.0.3",
    "nanobind>=3.0.1",
    "nanobind-backend>=1.0.0",
    "dspsim[verilator]",
]
build-backend = "scikit_build_core.build"

[project]
name = "some_example"
version = "0.0.1"
description = ""
requires-python = ">=3.14"
dependencies = [
    "dspsim[verilator]",
]

[tool.uv.sources]
dspsim = { path = "../../../dspsim" }

[tool.scikit-build]
minimum-version = "build-system.requires"
build-dir = "build"

[tool.uv]
cache-keys = [
    { file = "pyproject.toml" },
    { file = "src/**/*.{h,c,hpp,cpp,v,sv}" },
    { file = "CMakeLists.txt" },
    {file = "src/CMakeLists.txt"}
]


# Generate binding code for modules.

#---------------------------------------------------------------------------------------------------#
#---------------------------------------------------------------------------------------------------#

# dspsim tool configuration for the library module.
[tool.dspsim]
name = "library"
# Use all sources in the dspsim/hdl directory.
sources = ["src/some_example/hdl/*.sv", "src/dspsim/hdl/*.v"]
include_dirs = []
include_dspsim_library = true
# Can use fst on linux.
trace = "vcd"

# Global parameters applied to all modules.
[tool.dspsim.parameters]
DW = 24

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

#---------------------------------------------------------------------------------------------------#
#---------------------------------------------------------------------------------------------------#
