add_custom_target(all_tests)
macro(dspsim_add_test name)
    add_executable(${name} ${name}.cpp)
    target_link_libraries(${name} PRIVATE dspsim::dspsim-core)
    add_test(NAME ${name} COMMAND ${name})
    add_dependencies(all_tests ${name})
endmacro()

dspsim_add_test(test_hierarchy)
dspsim_add_test(test_dff)
dspsim_add_test(test_submodule)
