name: Build
on:
  pull_request:
  push:
    branches:
      - main
      - release/*

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: ./dist/*
  
  build_linux_wheels:
    name: Python cibuildwheel linux
    runs-on: ["ubuntu-latest"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build Linux wheels
        run: pipx run cibuildwheel --platform linux --output-dir ./dist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-linux
          path: ./dist/*.whl

  upload_pypi:
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs: [build_linux_wheels, build_sdist]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/dspsim
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          # unpacks all CIBW artifacts into dist/
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - name: publish distribution to pypi.org
        uses: pypa/gh-action-pypi-publish@release/v1